# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-Hosted-Linux


stages:
- stage: Test
  jobs:
  - job: Test01
    displayName: Test01
    pool: Self-Hosted-Linux
    steps:
    - script: echo Testing!